CREATE TABLE exercises(idex INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, type INTEGER, img TEXT);
INSERT INTO mytable(idex,name,type,img) VALUES (1,'Dips Two Benches','Arms','Dips Two Benches.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (2,'Kick back','Arms','Kick back.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (3,'Two hand Vertical Extension','Arms','Two hand Vertical Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (4,'Bar Vertical Extension','Arms','Bar Vertical Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (5,'Sit pulley Extension','Arms','Sit Poulie Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (6,'Unilateral pulley Extension','Arms','Unilateral Poulie Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (7,'pulley Extension supination','Arms','Poulie Extension supination.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (8,'String Horizontal Extension','Arms','String Horizontal Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (9,'pulley Extension','Arms','Poulie Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (10,'Rotate Curl','Arms','Rotate Curl.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (11,'Hammer Curl','Arms','Hammer Curl.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (12,'Hammer Curl Pupitre','Arms','Hammer Curl Pupitre.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (13,'Hammer Curk Bench','Arms','Hammer Curk Bench.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (14,'unilateral thigh press','Leg','unilateral thigh press.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (15,'Leg Extension','Leg','Leg Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (16,'Hack Squat','Leg','Hack Squat.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (17,'Calf Press','Leg','Calf Press.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (18,'Bar Calf Extension','Leg','Bar Calf Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (19,'Bench','Chest','Bench.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (20,'Bench Press Dumbbells','Chest','Bench Press Dumbbells.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (21,'incline press','Chest','incline press.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (22,'Push-up','Chest','push-up.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (23,'Deadlift','Back','Deadlift.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (24,'Traction suplination hand','Back','Traction suplination hand.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (25,'Traction','Back','Traction.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (26,'Vertical Pull','Back','Bent-Over.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (27,'Tight Grip Vertical Pull','Back','Tight Grip Vertical Pull.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (28,'Supine Vertical Draw','Back','Supine Vertical Draw.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (29,'One-Sided Vertical Draft','Back','One-Sided Vertical Draft.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (30,'Neck Press','Shoulders','Neck Press.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (31,'Dumbbell Press','Shoulders','Dumbbell Press.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (32,'Arnold Developed','Shoulders','Arnold Developed.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (33,'Machine Shoulder Press','Shoulders','Machine Shoulder Press.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (34,'Lying Lateral Raise','Shoulders','Lying Lateral Raise.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (35,'Low Pulley Lateral Raises','Shoulders','Low Pulley Lateral Raises.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (36,'Machine Lateral Raises','Shoulders','Machine Lateral Raises.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (37,'Dips Two Benches','Full body','Dips Two Benches.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (38,'Kick back','Full body','Kick back.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (39,'Two hand Vertical Extension','Full body','Two hand Vertical Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (40,'Bar Vertical Extension','Full body','Bar Vertical Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (41,'Sit pulley Extension','Full body','Sit Poulie Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (42,'Unilateral pulley Extension','Full body','Unilateral Poulie Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (43,'pulley Extension supination','Full body','Poulie Extension supination.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (44,'String Horizontal Extension','Full body','String Horizontal Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (45,'pulley Extension','Full body','Poulie Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (46,'Rotate Curl','Full body','Rotate Curl.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (47,'Hammer Curl','Full body','Hammer Curl.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (48,'Hammer Curl Pupitre','Full body','Hammer Curl Pupitre.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (49,'Hammer Curk Bench','Full body','Hammer Curk Bench.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (50,'unilateral thigh press','Full body','unilateral thigh press.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (51,'Leg Extension','Full body','Leg Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (52,'Hack Squat','Full body','Hack Squat.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (53,'Calf Press','Full body','Calf Press.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (54,'Bar Calf Extension','Full body','Bar Calf Extension.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (55,'Bench','Full body','Bench.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (56,'Bench Press Dumbbells','Full body','Bench Press Dumbbells.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (57,'incline press','Full body','incline press.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (58,'Push-up','Full body','push-up.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (59,'Deadlift','Full body','Deadlift.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (60,'Traction suplination hand','Full body','Traction suplination hand.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (61,'Traction','Full body','Traction.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (62,'Vertical Pull','Full body','Bent-Over.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (63,'Tight Grip Vertical Pull','Full body','Tight Grip Vertical Pull.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (64,'Supine Vertical Draw','Full body','Supine Vertical Draw.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (65,'One-Sided Vertical Draft','Full body','One-Sided Vertical Draft.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (66,'Neck Press','Full body','Neck Press.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (67,'Dumbbell Press','Full body','Dumbbell Press.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (68,'Arnold Developed','Full body','Arnold Developed.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (69,'Machine Shoulder Press','Full body','Machine Shoulder Press.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (70,'Lying Lateral Raise','Full body','Lying Lateral Raise.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (71,'Low Pulley Lateral Raises','Full body','Low Pulley Lateral Raises.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (72,'Machine Lateral Raises','Full body','Machine Lateral Raises.jpg');
INSERT INTO mytable(idex,name,type,img) VALUES (73,'Run','Cardio','Run.jpg');
